# Generated by Django 2.2 on 2019-08-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='unlike',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
